### ISSUE TITLE
MVPs, Schema, Backend Routes

### ISSUE THREAD

**Issue by gorterd** [ShahdiQ/Pinterested#1]
# MVP List

- I'd consider eliminating Profile as its own MVP, and instead doing Boards + Profile first, without the post sign-up profile setup nor the ability to edit user profile. Those could be moved to a bonus MVP, allowing you to focus on the core functionality of finding, saving, & creating pins and organizing them into boards. 
- I'd do Discover Feed after Pins and Boards (in meantime, user can be directed to their profile page after login/signup). Pins depend on boards, and Feed depends on pins. 
- Boards/Pins: remember to include edit and delete functionality as well!
- Discover / Profile: including hash tags / tuning home feed would mean quite a bit more backend work without a huge impact on frontend experience. I'd consider making that a bonus, focusing on the core functionality first.
- Likes & Comments: by likes, do you mean saving pins? If so, I'd include that with the Pins or Discover MVPs. 
- I'd consider making Follows a primary MVP and likes/comments a bonus; it seems more central to the user experience (navigating to users' profiles from discover page and following those you like).
- Follows: I'd include the ability to view other users' profiles here (which looks a bit different than the current users), or else include that with the Boards + Profile MVP.  
- I'd consider adding a Search bonus MVP.

# Database Schema
- Heads up for users table, name thru location columns: If, based on MVP feedback, you choose to wait to implement the full user profile (with edit ability) as a bonus, then these columns might not be necessary. Or, you could include something like first and last name fields in your signup form (and then have first_name and last_name columns)
- Pins: you do not need an image column. You'll attach images via active storage, which, on install, creates its own tables you never have to directly manage. - Boards: consider also including data about whether it's a secret board or not.
- Likes/Comments: for the polymorphic liked subject and commented subject references, Rails has a specific convention: verb-able_id and verb-able_type. E.g. likeable_id and likeable_type. See [polymorphic associations](https://guides.rubyonrails.org/association_basics.html#polymorphic-associations)
- Hashtags: should belong to a user, or there should be a hashtag + user joins table
- I'd add a joins table for saves. A single pin can be saved by many users, so it's many:many.
- You'll need a table for follows if you make that a primary MVP

Nice work, Shahdi! Let me know if you have questions

# Backend Routes

- Formatting problem w/ the root route (looks like the controller action is part of the url).
- Overall: the wildcard for non-nested routes (last wildcard for nested routes) should be :id, not :resource_id. 
- Overall: if any of your routes serve additional data related to the resource being requested (e.g. if GET api/users/:id serves data about a user's boards and follows too), be sure to mention that explicitly.
  - If you didn't intend to include additional data in your responses, you should consider! Thinking through the situations in which you'd need to request data from the backend, often times you need related data from other tables.
  - Example: when getting info about a board (GET api/boards/:id), you probably want that to include the pins contained in it.
  - If you *don't* include this data, then you need routes to get the pins for a specific board, the boards for a specific user, etc. GET api/boards for instance just represents a request for *all* boards. To have a route for a specific user's boards, you could do a nested route: api/users/:user_id/boards. Still goes to boards_controller#index, but with wildcard :user_id.
  - After making these adjustments, some routes might be unnecessary (for example, probably don't need GET api/boards)
- Need routes for saving pins
- What data is returned by GET api/hashtags/:id? When would this request be needed on frontend? If you're referring to the pins associated with a particular hashtag, consider using a nested pins route: api/hashtags/:hashtag_id/pins

**Comment by ShahdiQ** [comment]
If I remove profile as an MVP, that would only leave me with 6 as opposed to 7, is that fine? Or should I separate pins and boards into different MVPs that way I am back at 7? I grouped them together because they have very similar functionality, but I guess they are different because a board can contain many pins. I would like to keep the Profile MVP in for now to stay at 7 and also because I don't know another ideal way to allow the user to edit their profile information (unless I should have the user input everything at the start and not allow them to change their info). I would appreciate your thoughts and feedback on what the best course of action in that regard would be. Should I eliminate the profile MVP and have the user's profile contain information they added when signing up (therefore making the user unable to change it) which would allow me to spend more time focusing on boards, pins, and other aspects of my site? Or should I keep it as is to stay at 7 MVPs?
