### ISSUE TITLE
Design Docs: sample state/frontend routes

### ISSUE THREAD

**Issue by dsuh93** [ShahdiQ/Pinterested#2]
Hey Shahdi, great work on design docs! just one minor change but everything else looks good!

# Sample State
​
- [x] State shape is flat!
- [x]  State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language `(```javascript...```)`. This will display the state as a code block instead of a giant line of text
    - [x]  Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka `comments` inside of `posts`
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can't change
            - like count and a boolean on whether the user likes the post instead of a likes slice
​
### Comments
- [ ] comments slice looks like it should have some sort of `body` field, seems like it might also be missing in schema
​
# Frontend Routes
​
- [x]  Frontend routes contains wildcard variables written in `camelCase`
- [x]  Correctly formatted
    - [x]  Routes are displayed with inline coding text (backticks)
​
### Comments
- looks great!

**Comment by ShahdiQ** [comment]
Added body to my sample state as well as schema
